### ISSUE TITLE
Non sono un contributor...

### ISSUE THREAD

**Issue by shtra** [frcassi/3LinesStories#1]
Niente, era solo per avvertirti che non posso pushare.

**Comment by frcassi** [comment]
Dovrei aver risolto, non mi ricordavo di doverlo aggiungere manualmente

**Comment by shtra** [comment]
...Non riesco ancora.

**Comment by frcassi** [comment]
![image](https://user-images.githubusercontent.com/39331053/62951499-65d58600-bdea-11e9-9d16-6d960c693449.png)
Credo tu debba accettare in qualche modo

**Comment by shtra** [comment]
Ok, scusa, ero andata a vedere, ma non me l'aveva mostrato.
